spring:
  datasource:
    url: jdbc:mysql:///test?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 253261
    driver-class-name: com.mysql.cj.jdbc.Driver
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true
  application:
    name: boot
    druid:
      aop-patterns: com.xyh.admin.* #springbean监控
      filters: stat,wall,slf4j #所有开启的功能

      filter:
        stat: #SQL监控
          log-slow-millis: 1000
          log-slow-sql: true
          enabled: true
        wall: #防火墙
          enabled: true
          config:
            drop-table-allow: false

      stat-view-servlet: #监控页配置
        enabled: true
        login-password: admin
        login-username: admin
        reset-enable: false

      web-stat-filter:  #web监控
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


  #   type:
  redis:
    host: 192.168.19.129
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0




mybatis:
  # 可以不写全局配置文件，所有全局配置文件的配置都放在configuration配置项中即可
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration: # 指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true #驼峰命名



# management 是所有actuator的配置
# management.endpoint.端点名.xxxx  对某个端点的具体配置
management:
  endpoints:
    enabled-by-default: true  #默认开启所有监控端点  true
    web:
      exposure:
        include: '*' # 以web方式暴露所有端点

  endpoint:   #对某个端点的具体配置
    health:
      show-details: always
      enabled: true

    info:
      enabled: true

    beans:
      enabled: true

    metrics:
      enabled: true





