spring:
  datasource:
    url: jdbc:mysql:///test?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 253261
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.xyh.admin.* #springbean监控
      filters: stat,wall,slf4j #所有开启的功能

      filter:
        stat: #SQL监控
          log-slow-millis: 1000
          log-slow-sql: true
          enabled: true
        wall: #防火墙
          enabled: true
          config:
            drop-table-allow: false

      stat-view-servlet: #监控页配置
        enabled: true
        login-password: admin
        login-username: admin
        reset-enable: false

      web-stat-filter:  #web监控
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

  #   type:
  jdbc:
    template:
      query-timeout: 3



mybatis:
  # 可以不写全局配置文件，所有全局配置文件的配置都放在configuration配置项中即可
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration: # 指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true #驼峰命名

